# Generated by Django 3.2 on 2021-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='date of start')),
                ('end_date', models.DateField(verbose_name='date of end')),
                ('lectures_num', models.PositiveIntegerField(verbose_name='number of lectures')),
            ],
        ),
    ]
